name: Destroy EKS Cluster

on:
  workflow_dispatch: # Allows manual trigger of this workflow
  push:
    branches:
    - main # Optional: Run on push to the main branch

permissions:
  contents: read

jobs:
  terraform:
    name: Destroy EKS Cluster
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v4

    # Set up AWS credentials
    - name: Set AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV

    - name: Setup Terraform
      # Install Terraform CLI
      uses: hashicorp/setup-terraform@v1

    # Destroy the EKS Cluster
    - name: Terraform Destroy
      run: terraform destroy -auto-approve
